[versions]
agp = "8.13.2"
kotlin = "2.1.0"
composeBom = "2025.01.00"
coreKtx = "1.15.0"
lifecycle = "2.8.7"
activityCompose = "1.9.3"
concurrentFutures = "1.2.0"
ksp = "2.1.0-1.0.29"
room = "2.6.1"
coroutines = "1.9.0"

[libraries]
core-ktx           = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
lifecycle-runtime  = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
activity-compose   = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
activity-ktx       = { group = "androidx.activity", name = "activity-ktx", version.ref = "activityCompose" }
compose-bom        = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
compose-ui         = { group = "androidx.compose.ui", name = "ui" }
compose-graphics   = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-tooling    = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-material3  = { group = "androidx.compose.material3", name = "material3" }
concurrent-futures = { group = "androidx.concurrent", name = "concurrent-futures", version.ref = "concurrentFutures" }
room-runtime       = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-ktx           = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-compiler      = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android      = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose      = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-jvm          = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
android-library     = { id = "com.android.library", version.ref = "agp" }
ksp                 = { id = "com.google.devtools.ksp", version.ref = "ksp" }
